apiVersion: v1
kind: Pod
metadata:
  name: nginx-cm-pod
spec:
  containers:
    - name: nginx-cm-container
      image: nginx
      command: [ "/bin/sh", "-c", "env" ]
      env:
        # Define the environment variable
        - name: envname
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: cm-one
              # Specify the key associated with the value
              key: name
  restartPolicy: Never
