apiVersion: v1
kind: Pod
metadata:
  name: prometheus-csvserver
  namespace: csvserver
  labels:
    app: prometheus-csvserver
spec:
  containers:
  - name: prometheus-csvserver
    image: prom/prometheus:v2.22.0
    volumeMounts:
    - name: csvserver-prom-config-volume
      mountPath: "/etc/prometheus/prometheus.yml"
      subPath: prometheus.yml
    - name: prom-storage
      mountPath: "/prometheus"
      name: prom-pv-storage
    ports:
    - containerPort: 9090
  volumes:
  - name: csvserver-prom-config-volume
    configMap:
       name: cm-prom-csv
  - name: prom-pv-storage
    persistentVolumeClaim:
         claimName: csvserver-prom-pv-claim
    volumeMounts:
    - name: init-storage
      mountPath: "/prometheus"
      name: prom-pv-storage

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csvserver
  name: prom-csvserver-service
  namespace: csvserver
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus-csvserver
  type: LoadBalancer

